default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] || 'coak' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
  host: localhost

development:
  <<: *default
  database: anime_app_development

test:
  <<: *default
  database: anime_app_test

production:
  <<: *default
  database: anime_app_production
  username: anime_app
  password: <%= ENV["ANIME_APP_DATABASE_PASSWORD"] %>